Repository Software-development-methodology/tcp-ip-implementation, pull requests merged in 2025-05, with the labels that each got.

#4 25-05-01 회의록
  proto/meeting/25-05-01.md
  proto/meeting/resource/25_05_01_meeting_pic1.jpeg
Labels: documentation

#10 Spike header construction (yousung Jung)
  spike/issue9-header-construction/yousung-jung/README.md
  spike/issue9-header-construction/yousung-jung/header-construction-generic/.gitignore
  spike/issue9-header-construction/yousung-jung/header-construction-generic/.idea/.gitignore
  spike/issue9-header-construction/yousung-jung/header-construction-generic/.idea/gradle.xml
  spike/issue9-header-construction/yousung-jung/header-construction-generic/.idea/jpa-buddy.xml
  spike/issue9-header-construction/yousung-jung/header-construction-generic/.idea/misc.xml
  spike/issue9-header-construction/yousung-jung/header-construction-generic/.idea/vcs.xml
  spike/issue9-header-construction/yousung-jung/header-construction-generic/build.gradle
  spike/issue9-header-construction/yousung-jung/header-construction-generic/gradle/wrapper/gradle-wrapper.jar
  spike/issue9-header-construction/yousung-jung/header-construction-generic/gradle/wrapper/gradle-wrapper.properties
  spike/issue9-header-construction/yousung-jung/header-construction-generic/gradlew
  spike/issue9-header-construction/yousung-jung/header-construction-generic/gradlew.bat
  spike/issue9-header-construction/yousung-jung/header-construction-generic/settings.gradle
  spike/issue9-header-construction/yousung-jung/header-construction-generic/src/main/java/com/github/can019/Main.java
  spike/issue9-header-construction/yousung-jung/header-construction-generic/src/main/java/com/github/can019/core/data/chunk/Chunk.java
  spike/issue9-header-construction/yousung-jung/header-construction-generic/src/main/java/com/github/can019/core/data/chunk/header/EmptyHeader.java
  spike/issue9-header-construction/yousung-jung/header-construction-generic/src/main/java/com/github/can019/core/data/chunk/header/EmptyHeaderData.java
  spike/issue9-header-construction/yousung-jung/header-construction-generic/src/main/java/com/github/can019/core/data/chunk/header/FrameHeader.java
  spike/issue9-header-construction/yousung-jung/header-construction-generic/src/main/java/com/github/can019/core/data/chunk/header/FrameHeaderData.java
  spike/issue9-header-construction/yousung-jung/header-construction-generic/src/main/java/com/github/can019/core/data/chunk/header/Header.java
  spike/issue9-header-construction/yousung-jung/header-construction-generic/src/main/java/com/github/can019/core/data/chunk/header/HeaderData.java
  spike/issue9-header-construction/yousung-jung/header-construction-generic/src/main/java/com/github/can019/core/data/chunk/payload/Payload.java
  spike/issue9-header-construction/yousung-jung/header-construction-generic/src/main/java/com/github/can019/core/layer/EthernetLayer.java
  spike/issue9-header-construction/yousung-jung/header-construction-generic/src/main/java/com/github/can019/core/layer/Layer.java
  spike/issue9-header-construction/yousung-jung/header-construction/.gitignore
  spike/issue9-header-construction/yousung-jung/header-construction/.idea/.gitignore
  spike/issue9-header-construction/yousung-jung/header-construction/.idea/gradle.xml
  spike/issue9-header-construction/yousung-jung/header-construction/.idea/jpa-buddy.xml
  spike/issue9-header-construction/yousung-jung/header-construction/.idea/misc.xml
  spike/issue9-header-construction/yousung-jung/header-construction/.idea/vcs.xml
  spike/issue9-header-construction/yousung-jung/header-construction/build.gradle.kts
  spike/issue9-header-construction/yousung-jung/header-construction/gradle/wrapper/gradle-wrapper.jar
  spike/issue9-header-construction/yousung-jung/header-construction/gradle/wrapper/gradle-wrapper.properties
  spike/issue9-header-construction/yousung-jung/header-construction/gradlew
  spike/issue9-header-construction/yousung-jung/header-construction/gradlew.bat
  spike/issue9-header-construction/yousung-jung/header-construction/settings.gradle.kts
  spike/issue9-header-construction/yousung-jung/header-construction/src/main/java/com/github/can019/Main.java
  spike/issue9-header-construction/yousung-jung/header-construction/src/main/java/com/github/can019/core/data/Chunk.java
  spike/issue9-header-construction/yousung-jung/header-construction/src/main/java/com/github/can019/core/data/Payload.java
  spike/issue9-header-construction/yousung-jung/header-construction/src/main/java/com/github/can019/core/data/header/Header.java
  spike/issue9-header-construction/yousung-jung/header-construction/src/main/java/com/github/can019/core/data/header/implement/FrameHeader.java
  spike/issue9-header-construction/yousung-jung/header-construction/src/main/java/com/github/can019/core/data/header/implement/PacketHeader.java
  spike/issue9-header-construction/yousung-jung/header-construction/src/main/java/com/github/can019/core/layer/Layer.java
  spike/issue9-header-construction/yousung-jung/header-construction/src/main/java/com/github/can019/core/layer/implement/EthernetLayer.java
  spike/issue9-header-construction/yousung-jung/header-construction/src/main/java/com/github/can019/core/layer/implement/InternetLayer.java
  spike/issue9-header-construction/yousung-jung/header-construction/src/test/java/com/github/can019/core/layer/implement/EthernetLayerTest.java
  spike/issue9-header-construction/yousung-jung/header-construction/src/test/java/com/github/can019/core/layer/implement/InternetLayerTest.java
Labels: group spike

#15 Spike issue9 header construction/hoyoung jung CHUNK FACTORY
  .idea/.gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/libraries/Gradle__org_apiguardian_apiguardian_api_1_1_2.xml
  .idea/libraries/Gradle__org_junit_jupiter_junit_jupiter_5_10_0.xml
  .idea/libraries/Gradle__org_junit_jupiter_junit_jupiter_api_5_10_0.xml
  .idea/libraries/Gradle__org_junit_jupiter_junit_jupiter_engine_5_10_0.xml
  .idea/libraries/Gradle__org_junit_jupiter_junit_jupiter_params_5_10_0.xml
  .idea/libraries/Gradle__org_junit_platform_junit_platform_commons_1_10_0.xml
  .idea/libraries/Gradle__org_junit_platform_junit_platform_engine_1_10_0.xml
  .idea/libraries/Gradle__org_opentest4j_opentest4j_1_3_0.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/header-construction.iml
  .idea/modules/header-construction.main.iml
  .idea/modules/header-construction.test.iml
  .idea/tcp-ip-implementation.iml
  .idea/vcs.xml
  spike/issue9-header-construction/hoyoung-jung/header-construction/.gitignore
  spike/issue9-header-construction/hoyoung-jung/header-construction/.idea/.gitignore
  spike/issue9-header-construction/hoyoung-jung/header-construction/.idea/gradle.xml
  spike/issue9-header-construction/hoyoung-jung/header-construction/.idea/misc.xml
  spike/issue9-header-construction/hoyoung-jung/header-construction/.idea/vcs.xml
  spike/issue9-header-construction/hoyoung-jung/header-construction/build.gradle.kts
  spike/issue9-header-construction/hoyoung-jung/header-construction/gradle/wrapper/gradle-wrapper.jar
  spike/issue9-header-construction/hoyoung-jung/header-construction/gradle/wrapper/gradle-wrapper.properties
  spike/issue9-header-construction/hoyoung-jung/header-construction/gradlew
  spike/issue9-header-construction/hoyoung-jung/header-construction/gradlew.bat
  spike/issue9-header-construction/hoyoung-jung/header-construction/settings.gradle.kts
  spike/issue9-header-construction/hoyoung-jung/header-construction/src/main/java/Main.java
Labels: group spike

#19 Spike Header (Sumin Park)
  spike/issue9-header-construction/sumain-park/src/Main.java
  spike/issue9-header-construction/sumain-park/src/chunk/Chunk.java
  spike/issue9-header-construction/sumain-park/src/gui/Gui.java
  spike/issue9-header-construction/sumain-park/src/header/FrameHeader.java
  spike/issue9-header-construction/sumain-park/src/header/Header.java
  spike/issue9-header-construction/sumain-park/src/header/HeaderCreator.java
  spike/issue9-header-construction/sumain-park/src/header/HttpMessageHeader.java
  spike/issue9-header-construction/sumain-park/src/header/PacketHeader.java
  spike/issue9-header-construction/sumain-park/src/header/SegmentHeader.java
  spike/issue9-header-construction/sumain-park/src/layer/Layer.java
  spike/issue9-header-construction/sumain-park/src/layer/MockNetworkInterfaceLayer.java
Labels: group spike

#20 Junit 5 Ci
  .github/workflows/ci.yml
Labels: enhancement

#17 Data 추상화 및 abstract Layer 작성
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/github/software_development_methodology_study/Main.java
  src/main/java/com/github/software_development_methodology_study/core/data/chunk/Chunk.java
  src/main/java/com/github/software_development_methodology_study/core/data/chunk/header/EmptyHeader.java
  src/main/java/com/github/software_development_methodology_study/core/data/chunk/header/Header.java
  src/main/java/com/github/software_development_methodology_study/core/data/chunk/payload/Payload.java
  src/main/java/com/github/software_development_methodology_study/core/data/contract/FixedSize.java
  src/main/java/com/github/software_development_methodology_study/core/layer/Layer.java
  src/test/java/com/github/software_development_methodology_study/core/layer/LayerTest.java
  src/test/java/com/github/software_development_methodology_study/core/layer/TestHeader.java
  src/test/java/com/github/software_development_methodology_study/core/layer/TestLayer.java
  src/test/java/com/github/software_development_methodology_study/core/layer/TestLayer2.java
Labels: enhancement

#22 25-05-15 회의록
  .idea/.gitignore
  .idea/dbnavigator.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/tcp-ip-implementation.iml
  .idea/vcs.xml
  proto/meeting/25-05-15.md
Labels: documentation

#29 [CI] PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ci

#31 [CI] Junit5 multi OS 대응
  .github/workflows/ci.yml
Labels: ci
